Primeira versão.
pet-estatistica/pet-estatistica.github.io pull request #19
Opened 2021-01-20 21:44 UTC by caiogomesalves

## Propósito deste Pull Request

 - [X] Novo post no blog
 - [ ] Alterações em uma página estática
 - [ ] Alteração de configuração geral do site
 - [ ] Nova página estática
 
 ## Descrição breve das alterações
 Novo post do petiano Caio, com o tema: A Probabilidade nos Jogos de Azar: O Jogo do Bicho. Necessita análise para conferir possíveis erros, melhorias e alterações.

 ## Responsáveis
Caio Gomes Alves
 
 ## Endereço para pré-visualização
 
 https://caio_post3--pet-est.netlify.app/

2021-01-27 19:05 UTC, DaviYokogawa approved these changes
Não encontrei nada a ser alterado, parabéns pelo post.

2021-01-28 20:56 UTC, Marcelo-Jose approved these changes

2021-02-04 20:42 UTC, f-melo commented on content/post/2021-01-20-a-probabilidade-nos-jogos-de-azar-o-jogo-do-bicho/index.pt.Rmd
> +Com o crescimento da popularidade do Jogo do Bicho em diversas cidades por todo o Brasil, o Jogo do Bicho começou a ter diversos problemas com a Lei. Mas engana-se quem acha que demorou para surgirem
```suggestion
Com o crescimento da popularidade do Jogo do Bicho em diversas cidades por todo o Brasil, o Jogo do Bicho começou a ter diversos problemas com a Lei. Mas engana-se quem acha que demorou para surgirem esses problemas. A primeira notificação formal da Polícia para com o Bicho foi feita apenas duas semanas de sua criação.
```

2021-02-28 22:03 UTC, caiogomesalves commented on content/post/2021-01-20-a-probabilidade-nos-jogos-de-azar-o-jogo-do-bicho/index.pt.Rmd
> +Com o crescimento da popularidade do Jogo do Bicho em diversas cidades por todo o Brasil, o Jogo do Bicho começou a ter diversos problemas com a Lei. Mas engana-se quem acha que demorou para surgirem
```suggestion
Com o crescimento da popularidade do Jogo do Bicho em diversas cidades por todo o Brasil, o Jogo do Bicho começou a ter diversos problemas com a Lei. Mas engana-se quem acha que demorou para surgirem esses problemas. A primeira notificação formal da Polícia para com o Bicho foi feita apenas duas semanas após a sua criação.
```

2021-03-03 20:42 UTC, fernandomayer requested changes
O post não está aparecendo porque está no diretório `content/post/...` 

O arquivo Rmd precisa estar no `content/blog/...` Quando for criar o post no Rstudio lembre que no "Subdirectory" tem que mudar para "blog"

![Screenshot from 2021-03-03 17-39-46](https://user-images.githubusercontent.com/650253/109869392-8d4ba800-7c47-11eb-8b7f-59615d15ab9f.png)

Sugiro copiar o conteúdo desse post e criar outro.

2021-03-08 17:56 UTC, caiogomesalves commented
O post já aparece na tela inicial, devido à alteração de subdiretório.

2021-03-09 23:38 UTC, fernandomayer commented on content/blog/A_Probabilidade_nos_Jogos_de_Azar_Jogo_Do_Bicho.Rmd
> +Continuando a série de posts sobre jogos de azar, vamos dar uma olhada na probabilidade por trás de um dos jogos mais tradicionais das terras Tupiniquins: O Jogo do Bicho.
Essa frase pode ir ali pra cima no campo `description`

2021-03-09 23:39 UTC, fernandomayer commented on content/blog/A_Probabilidade_nos_Jogos_de_Azar_Jogo_Do_Bicho.Rmd
> +images:
Tente colocar uma imagem relacionada, como a do outro post. Vai chamar mais a atenção

2021-03-09 23:40 UTC, fernandomayer reviewed
O texto ta muito bom, só falta uma imagem ali no começo

2021-03-29 23:52 UTC, fernandomayer approved these changes

2021-03-29 23:53 UTC, merged